In [1]:
# tutorial 2-2 "numpy", "scipy"

In [30]:
import numpy as np
import scipy as sp
import math
import time
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
np.sin(1)

0.8414709848078965

In [4]:
np.pi

3.141592653589793

In [5]:
sin_list = []
for i in range(21):
    sin_list.append(np.sin(i * np.pi / 10))
print(sin_list)
#maybe numpy sin function is defined as 0 <= np.pi < 2 * np.pi

[0.0, 0.3090169943749474, 0.5877852522924731, 0.8090169943749473, 0.9510565162951535, 1.0, 0.9510565162951536, 0.8090169943749475, 0.5877852522924732, 0.3090169943749475, 1.2246467991473532e-16, -0.3090169943749469, -0.587785252292473, -0.8090169943749473, -0.9510565162951535, -1.0, -0.9510565162951536, -0.8090169943749476, -0.5877852522924732, -0.3090169943749476, -2.4492935982947064e-16]


In [6]:
integer_list = [n for n in range (1, 11)]
integer_list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [7]:
# convert list to array
integer_array = np.array(integer_list)
print(integer_array)

[ 1  2  3  4  5  6  7  8  9 10]


In [8]:
# create array
# np.arange(start, stop, step)
# the range doesn't include the last number
another_integer_array = np.arange(1, 11)
print(another_integer_array)

aee = np.arange(1, 11, 0.5)
print(aee)

[ 1  2  3  4  5  6  7  8  9 10]
[ 1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.   7.5
  8.   8.5  9.   9.5 10.  10.5]


In [9]:
k = [[1, 2 ,3], [4, 5, 6]]

np.array(k)
print(np.array(k))

[[1 2 3]
 [4 5 6]]


In [10]:
kk = np.array([[[1, 2], [3, 4], [5, 6]], [[1, 2], [3, 4], [5, 6]]])

print(kk)

print(np.shape(kk))
#(2, 3, 2) is a "shape" of the array

[[[1 2]
  [3 4]
  [5 6]]

 [[1 2]
  [3 4]
  [5 6]]]
(2, 3, 2)


In [11]:
print(integer_array)

sin_integer_array = np.sin(integer_array)

print(sin_integer_array)

print(np.exp(integer_array))

#sin, cos, exponential, logarithmic etc. are called "universal function" or "ufunc" in numpy.

[ 1  2  3  4  5  6  7  8  9 10]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155
  0.6569866   0.98935825  0.41211849 -0.54402111]
[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
 8.10308393e+03 2.20264658e+04]


In [12]:
lots_of_ones = np.ones(10)

print(lots_of_ones)

lots_of_fives = 5 * lots_of_ones

print(lots_of_fives)

print(2**lots_of_fives)
#2^5

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
[32. 32. 32. 32. 32. 32. 32. 32. 32. 32.]


In [13]:
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

print(A + B)
print(A - B)
print(A * B)
print(A / B)


[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [14]:
integer_list = [n for n in range(1, 11)]
integer_array = np.array(integer_list)
another_integer_array = np.arange(1,11)

print(integer_list)
print(integer_array)
print(another_integer_array)

print(type(integer_list))
print(type(integer_array))
print(type(another_integer_array))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]
<class 'list'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [15]:
print(np.sin(integer_array))
print(np.cos(integer_array))
print(np.exp(integer_array))

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155
  0.6569866   0.98935825  0.41211849 -0.54402111]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219  0.96017029
  0.75390225 -0.14550003 -0.91113026 -0.83907153]
[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
 8.10308393e+03 2.20264658e+04]


In [16]:
test_array = np.ones(11)
array_1 = 3 * test_array
array_2 = 5 * test_array
test_array = array_1 + array_2
test_array = test_array / 4
print(test_array)

[2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]


In [17]:
hello = np.zeros(9)
goodbye = np.arange(1, 19, 2)
hello = 3 * (hello + 1)

print(hello)
test_array = (hello + goodbye) ** 2 #2乗!!

print(test_array)

[3. 3. 3. 3. 3. 3. 3. 3. 3.]
[ 16.  36.  64. 100. 144. 196. 256. 324. 400.]


In [18]:
luke = np.ones(7)
leah = 2 * luke
han = 3 * luke
darth = 4 * luke
jabba = 5 * luke
(luke + leah) * han * (darth - jabba)
#operation by each component

array([-9., -9., -9., -9., -9., -9., -9.])

In [19]:
charm = np.pi * np.ones(20) / 2

bottom = np.sin(charm)
print(bottom)

up = np.cos(charm)
print(up)
#agin, almost 0 but not defined!

test_array = bottom * up
print(test_array)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[6.123234e-17 6.123234e-17 6.123234e-17 6.123234e-17 6.123234e-17
 6.123234e-17 6.123234e-17 6.123234e-17 6.123234e-17 6.123234e-17
 6.123234e-17 6.123234e-17 6.123234e-17 6.123234e-17 6.123234e-17
 6.123234e-17 6.123234e-17 6.123234e-17 6.123234e-17 6.123234e-17]
[6.123234e-17 6.123234e-17 6.123234e-17 6.123234e-17 6.123234e-17
 6.123234e-17 6.123234e-17 6.123234e-17 6.123234e-17 6.123234e-17
 6.123234e-17 6.123234e-17 6.123234e-17 6.123234e-17 6.123234e-17
 6.123234e-17 6.123234e-17 6.123234e-17 6.123234e-17 6.123234e-17]


In [20]:
l =[]
for i in range(5):
    l.append(i^2)
print(l)

#listをarrayにするの忘れずに
test_array2 = np.array(l)
print(test_array2)

test_array2 = test_array2 / 4
test_array2 = np.sin(test_array2)
heisenberg = test_array2 ** 2
schrodinger = test_array2 ** 3
pauli = test_array2
print(pauli)
test_array2 = (heisenberg + schrodinger + pauli) ** 2
print(test_array2)

[2, 3, 0, 1, 6]
[2 3 0 1 6]
[0.47942554 0.68163876 0.         0.24740396 0.99749499]
[0.67153074 2.1403132  0.         0.10481792 8.91019518]


In [21]:
nested_list = [[1, 2, 3], [4, 5, 6]]
print(nested_list)

#listもarrayも0から始まる
print(nested_list[1][1])      

two_dim_array = np.array(nested_list)

print(two_dim_array)

#１行１列
print(two_dim_array[1, 1])

#reassign
two_dim_array[1, 1] = 13

print(two_dim_array)

[[1, 2, 3], [4, 5, 6]]
5
[[1 2 3]
 [4 5 6]]
5
[[ 1  2  3]
 [ 4 13  6]]


In [22]:
math_sin =[]
numpy_sin = []

for i in range(9):
    math_sin.append(math.sin(i*np.pi/2))
    numpy_sin.append(np.sin(i*np.pi/2))

print(math_sin)
print(numpy_sin)

#何が違う？？？？？？？

[0.0, 1.0, 1.2246467991473532e-16, -1.0, -2.4492935982947064e-16, 1.0, 3.6739403974420594e-16, -1.0, -4.898587196589413e-16]
[0.0, 1.0, 1.2246467991473532e-16, -1.0, -2.4492935982947064e-16, 1.0, 3.6739403974420594e-16, -1.0, -4.898587196589413e-16]


In [23]:
by_list_loop =[]
for i in range(10):
    by_list_loop.append(i)
    
print(by_list_loop)

array_list_loop = np.array(by_list_loop)
print(array_list_loop)

by_list_comprehention = [n for n in range(10)]

print(by_list_comprehention)

array_list_comprehention = np.array(by_list_comprehention)
print(array_list_comprehention)

array_numpycommands = np.arange(0, 10, 1)
print(array_numpycommands)

print(np.shape(array_numpycommands))

#zeroo_list = []
#for n in range(50):
    #zeroo_list.append(n*0)

#print(zeroo_list)

#zeroo = np.array(zeroo_list)

#print(zeroo)
#print(np.shape(zeroo))

#This command makes array!!
zero = np.zeros(50)

print(zero)
print(np.shape(zero))

#shape(1, 50)??
    
    
seventh_3 = np.zeros(25)

seventh_3[6] = 3
print(seventh_3)



[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0 1 2 3 4 5 6 7 8 9]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
(10,)
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0.]
(50,)
[0. 0. 0. 0. 0. 0. 3. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0.]


In [24]:
special_array = np.zeros(753)
for n in range(377):
    special_array[2*n] = (2*n)**2

print(special_array)

[0.00000e+00 0.00000e+00 4.00000e+00 0.00000e+00 1.60000e+01 0.00000e+00
 3.60000e+01 0.00000e+00 6.40000e+01 0.00000e+00 1.00000e+02 0.00000e+00
 1.44000e+02 0.00000e+00 1.96000e+02 0.00000e+00 2.56000e+02 0.00000e+00
 3.24000e+02 0.00000e+00 4.00000e+02 0.00000e+00 4.84000e+02 0.00000e+00
 5.76000e+02 0.00000e+00 6.76000e+02 0.00000e+00 7.84000e+02 0.00000e+00
 9.00000e+02 0.00000e+00 1.02400e+03 0.00000e+00 1.15600e+03 0.00000e+00
 1.29600e+03 0.00000e+00 1.44400e+03 0.00000e+00 1.60000e+03 0.00000e+00
 1.76400e+03 0.00000e+00 1.93600e+03 0.00000e+00 2.11600e+03 0.00000e+00
 2.30400e+03 0.00000e+00 2.50000e+03 0.00000e+00 2.70400e+03 0.00000e+00
 2.91600e+03 0.00000e+00 3.13600e+03 0.00000e+00 3.36400e+03 0.00000e+00
 3.60000e+03 0.00000e+00 3.84400e+03 0.00000e+00 4.09600e+03 0.00000e+00
 4.35600e+03 0.00000e+00 4.62400e+03 0.00000e+00 4.90000e+03 0.00000e+00
 5.18400e+03 0.00000e+00 5.47600e+03 0.00000e+00 5.77600e+03 0.00000e+00
 6.08400e+03 0.00000e+00 6.40000e+03 0.00000e+00 6.

In [25]:
# np.random.rand(行, 列) * a + b  bは最小値, aは最大値

a = np.random.rand(10) * 40 + 30
print(a)

b = np.random.rand(5, 5) * 1 + 0
print(b)

[37.67032753 44.83986893 64.63236851 34.64576448 46.49049675 65.79073001
 32.87308725 69.9824136  68.16716732 66.74034029]
[[0.58781239 0.12583512 0.77882895 0.41650042 0.59092718]
 [0.7206604  0.8549616  0.58384961 0.06027791 0.10196452]
 [0.24036367 0.36039774 0.6555177  0.57701688 0.25726304]
 [0.02913378 0.91597821 0.79658554 0.58906311 0.8278485 ]
 [0.75571636 0.1926585  0.71399389 0.39932433 0.51855907]]


In [26]:
v = 5

X = []
for t in range(20):
    X.append(5*(0.3*t))

x = np.array(X)
print(x)

[ 0.   1.5  3.   4.5  6.   7.5  9.  10.5 12.  13.5 15.  16.5 18.  19.5
 21.  22.5 24.  25.5 27.  28.5]


In [27]:
%%timeit

list_of_squares = []
for i in range(100000000):
    list_of_squares.append(i ** 2)
    
#It just takes time, Idk why

In [28]:
%%timeit

another_list_of_squares = [n ** 2 for n in range(10000000)]

In [29]:
%%timeit

numpy_list_of_squares = np. arange(10000000) ** 2